# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sessionUi.ui'
#
# Created: Mon Sep 22 19:59:31 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_session_form(object):
    def setupUi(self, session_form):
        session_form.setObjectName("session_form")
        session_form.resize(452, 532)
        self.centralwidget = QtGui.QWidget(session_form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sessionGB = QtGui.QGroupBox(self.centralwidget)
        self.sessionGB.setObjectName("sessionGB")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.sessionGB)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sessionsCB = QtGui.QComboBox(self.sessionGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionsCB.sizePolicy().hasHeightForWidth())
        self.sessionsCB.setSizePolicy(sizePolicy)
        self.sessionsCB.setObjectName("sessionsCB")
        self.horizontalLayout_6.addWidget(self.sessionsCB)
        self.setSessionPB = QtGui.QPushButton(self.sessionGB)
        self.setSessionPB.setObjectName("setSessionPB")
        self.horizontalLayout_6.addWidget(self.setSessionPB)
        self.verticalLayout_2.addWidget(self.sessionGB)
        self.actionsGB = QtGui.QGroupBox(self.centralwidget)
        self.actionsGB.setObjectName("actionsGB")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.actionsGB)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.actionsCB = QtGui.QComboBox(self.actionsGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionsCB.sizePolicy().hasHeightForWidth())
        self.actionsCB.setSizePolicy(sizePolicy)
        self.actionsCB.setObjectName("actionsCB")
        self.horizontalLayout_4.addWidget(self.actionsCB)
        self.addPB = QtGui.QPushButton(self.actionsGB)
        self.addPB.setObjectName("addPB")
        self.horizontalLayout_4.addWidget(self.addPB)
        self.verticalLayout_2.addWidget(self.actionsGB)
        self.currentSessionGB = QtGui.QGroupBox(self.centralwidget)
        self.currentSessionGB.setObjectName("currentSessionGB")
        self.verticalLayout = QtGui.QVBoxLayout(self.currentSessionGB)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sessionSCR = QtGui.QScrollArea(self.currentSessionGB)
        self.sessionSCR.setWidgetResizable(True)
        self.sessionSCR.setObjectName("sessionSCR")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 422, 300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sessionSCR.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.sessionSCR)
        self.savePB = QtGui.QPushButton(self.currentSessionGB)
        self.savePB.setObjectName("savePB")
        self.verticalLayout.addWidget(self.savePB)
        self.verticalLayout_2.addWidget(self.currentSessionGB)
        self.runsGB = QtGui.QGroupBox(self.centralwidget)
        self.runsGB.setTitle("")
        self.runsGB.setObjectName("runsGB")
        self.horizontalLayout = QtGui.QHBoxLayout(self.runsGB)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.executePB = QtGui.QPushButton(self.runsGB)
        self.executePB.setObjectName("executePB")
        self.horizontalLayout.addWidget(self.executePB)
        self.setDefaultPB = QtGui.QPushButton(self.runsGB)
        self.setDefaultPB.setObjectName("setDefaultPB")
        self.horizontalLayout.addWidget(self.setDefaultPB)
        self.verticalLayout_2.addWidget(self.runsGB)
        session_form.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(session_form)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        session_form.setMenuBar(self.menuBar)
        self.actionSession_Path = QtGui.QAction(session_form)
        self.actionSession_Path.setObjectName("actionSession_Path")
        self.menuSettings.addAction(self.actionSession_Path)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(session_form)
        QtCore.QMetaObject.connectSlotsByName(session_form)

    def retranslateUi(self, session_form):
        session_form.setWindowTitle(QtGui.QApplication.translate("session_form", "Master Reload V 2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.sessionGB.setTitle(QtGui.QApplication.translate("session_form", "Sessions", None, QtGui.QApplication.UnicodeUTF8))
        self.setSessionPB.setText(QtGui.QApplication.translate("session_form", "SET", None, QtGui.QApplication.UnicodeUTF8))
        self.actionsGB.setTitle(QtGui.QApplication.translate("session_form", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.addPB.setText(QtGui.QApplication.translate("session_form", "ADD", None, QtGui.QApplication.UnicodeUTF8))
        self.currentSessionGB.setTitle(QtGui.QApplication.translate("session_form", "Current session", None, QtGui.QApplication.UnicodeUTF8))
        self.savePB.setText(QtGui.QApplication.translate("session_form", "&Save session", None, QtGui.QApplication.UnicodeUTF8))
        self.executePB.setText(QtGui.QApplication.translate("session_form", "&excute", None, QtGui.QApplication.UnicodeUTF8))
        self.setDefaultPB.setText(QtGui.QApplication.translate("session_form", "&SetDefault", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("session_form", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSession_Path.setText(QtGui.QApplication.translate("session_form", "Set session &Path", None, QtGui.QApplication.UnicodeUTF8))

